spring:
  application:
    name: test-sc-4-13
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    timeout: 1000
swagger:
  base-package: com.deepexi.controller
  info:
    title: test-sc-4-13
server:
  error:
    include-stacktrace: always
    include-exception: true
logging:
  file: 'logs/${spring.application.name}.log'
eureka:
  client:
    service-url:
      defaultZone: 'http://user:pass@127.0.0.1:8761/eureka/'
mybatis:
  mapper-locations: 'classpath:mapper/*.xml'
feign:
  hystrix:
    enabled: true
shiro:
  web:
    mode: stateless
    filter-chain-definition:
      authc:
        - /v1/**
      anon:
        - /**
